version: "3.8"
services:
  server:
    build: .
    ports:
      - "3000:3000"
    env_file: ./server/.env.production
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD","mongosh","--eval","db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  mongo-data:
