version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/todo
    depends_on:
      - mongodb

  client:
    build: ./client
    ports:
      - "4173:4173"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
